# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token_Auth', models.CharField(max_length=255)),
                ('Token_Auth_Secret', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitt.User'),
        ),
    ]
